// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/blog.proto

package blog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderBy int32

const (
	OrderBy_readCount OrderBy = 0
	OrderBy_zanCount  OrderBy = 1
	OrderBy_ctime     OrderBy = 2
	OrderBy_mtime     OrderBy = 3
)

var OrderBy_name = map[int32]string{
	0: "readCount",
	1: "zanCount",
	2: "ctime",
	3: "mtime",
}

var OrderBy_value = map[string]int32{
	"readCount": 0,
	"zanCount":  1,
	"ctime":     2,
	"mtime":     3,
}

func (x OrderBy) String() string {
	return proto.EnumName(OrderBy_name, int32(x))
}

func (OrderBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{0}
}

type BlogIndexReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogIndexReq) Reset()         { *m = BlogIndexReq{} }
func (m *BlogIndexReq) String() string { return proto.CompactTextString(m) }
func (*BlogIndexReq) ProtoMessage()    {}
func (*BlogIndexReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{0}
}

func (m *BlogIndexReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogIndexReq.Unmarshal(m, b)
}
func (m *BlogIndexReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogIndexReq.Marshal(b, m, deterministic)
}
func (m *BlogIndexReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogIndexReq.Merge(m, src)
}
func (m *BlogIndexReq) XXX_Size() int {
	return xxx_messageInfo_BlogIndexReq.Size(m)
}
func (m *BlogIndexReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogIndexReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlogIndexReq proto.InternalMessageInfo

type BlogIndexResp struct {
	Articles             []*BlogArticle      `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	Cat                  map[int32]*Category `protobuf:"bytes,2,rep,name=cat,proto3" json:"cat,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlogIndexResp) Reset()         { *m = BlogIndexResp{} }
func (m *BlogIndexResp) String() string { return proto.CompactTextString(m) }
func (*BlogIndexResp) ProtoMessage()    {}
func (*BlogIndexResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{1}
}

func (m *BlogIndexResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogIndexResp.Unmarshal(m, b)
}
func (m *BlogIndexResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogIndexResp.Marshal(b, m, deterministic)
}
func (m *BlogIndexResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogIndexResp.Merge(m, src)
}
func (m *BlogIndexResp) XXX_Size() int {
	return xxx_messageInfo_BlogIndexResp.Size(m)
}
func (m *BlogIndexResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogIndexResp.DiscardUnknown(m)
}

var xxx_messageInfo_BlogIndexResp proto.InternalMessageInfo

func (m *BlogIndexResp) GetArticles() []*BlogArticle {
	if m != nil {
		return m.Articles
	}
	return nil
}

func (m *BlogIndexResp) GetCat() map[int32]*Category {
	if m != nil {
		return m.Cat
	}
	return nil
}

type BlogArticleReq struct {
	Oid                  string   `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogArticleReq) Reset()         { *m = BlogArticleReq{} }
func (m *BlogArticleReq) String() string { return proto.CompactTextString(m) }
func (*BlogArticleReq) ProtoMessage()    {}
func (*BlogArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{2}
}

func (m *BlogArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogArticleReq.Unmarshal(m, b)
}
func (m *BlogArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogArticleReq.Marshal(b, m, deterministic)
}
func (m *BlogArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogArticleReq.Merge(m, src)
}
func (m *BlogArticleReq) XXX_Size() int {
	return xxx_messageInfo_BlogArticleReq.Size(m)
}
func (m *BlogArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlogArticleReq proto.InternalMessageInfo

func (m *BlogArticleReq) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

type BlogArticleResp struct {
	Article              *BlogArticle        `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Cat                  map[int32]*Category `protobuf:"bytes,2,rep,name=cat,proto3" json:"cat,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BlogArticleResp) Reset()         { *m = BlogArticleResp{} }
func (m *BlogArticleResp) String() string { return proto.CompactTextString(m) }
func (*BlogArticleResp) ProtoMessage()    {}
func (*BlogArticleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{3}
}

func (m *BlogArticleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogArticleResp.Unmarshal(m, b)
}
func (m *BlogArticleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogArticleResp.Marshal(b, m, deterministic)
}
func (m *BlogArticleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogArticleResp.Merge(m, src)
}
func (m *BlogArticleResp) XXX_Size() int {
	return xxx_messageInfo_BlogArticleResp.Size(m)
}
func (m *BlogArticleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogArticleResp.DiscardUnknown(m)
}

var xxx_messageInfo_BlogArticleResp proto.InternalMessageInfo

func (m *BlogArticleResp) GetArticle() *BlogArticle {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *BlogArticleResp) GetCat() map[int32]*Category {
	if m != nil {
		return m.Cat
	}
	return nil
}

type Category struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Pcid                 int32    `protobuf:"varint,2,opt,name=pcid,proto3" json:"pcid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{4}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Category) GetPcid() int32 {
	if m != nil {
		return m.Pcid
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BlogListReq struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Order                OrderBy  `protobuf:"varint,3,opt,name=order,proto3,enum=OrderBy" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogListReq) Reset()         { *m = BlogListReq{} }
func (m *BlogListReq) String() string { return proto.CompactTextString(m) }
func (*BlogListReq) ProtoMessage()    {}
func (*BlogListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{5}
}

func (m *BlogListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogListReq.Unmarshal(m, b)
}
func (m *BlogListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogListReq.Marshal(b, m, deterministic)
}
func (m *BlogListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogListReq.Merge(m, src)
}
func (m *BlogListReq) XXX_Size() int {
	return xxx_messageInfo_BlogListReq.Size(m)
}
func (m *BlogListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlogListReq proto.InternalMessageInfo

func (m *BlogListReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BlogListReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BlogListReq) GetOrder() OrderBy {
	if m != nil {
		return m.Order
	}
	return OrderBy_readCount
}

type BlogListResp struct {
	List                 []*BlogArticle `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlogListResp) Reset()         { *m = BlogListResp{} }
func (m *BlogListResp) String() string { return proto.CompactTextString(m) }
func (*BlogListResp) ProtoMessage()    {}
func (*BlogListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{6}
}

func (m *BlogListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogListResp.Unmarshal(m, b)
}
func (m *BlogListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogListResp.Marshal(b, m, deterministic)
}
func (m *BlogListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogListResp.Merge(m, src)
}
func (m *BlogListResp) XXX_Size() int {
	return xxx_messageInfo_BlogListResp.Size(m)
}
func (m *BlogListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogListResp.DiscardUnknown(m)
}

var xxx_messageInfo_BlogListResp proto.InternalMessageInfo

func (m *BlogListResp) GetList() []*BlogArticle {
	if m != nil {
		return m.List
	}
	return nil
}

type BlogAddReq struct {
	Article              *BlogArticle `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlogAddReq) Reset()         { *m = BlogAddReq{} }
func (m *BlogAddReq) String() string { return proto.CompactTextString(m) }
func (*BlogAddReq) ProtoMessage()    {}
func (*BlogAddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{7}
}

func (m *BlogAddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogAddReq.Unmarshal(m, b)
}
func (m *BlogAddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogAddReq.Marshal(b, m, deterministic)
}
func (m *BlogAddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogAddReq.Merge(m, src)
}
func (m *BlogAddReq) XXX_Size() int {
	return xxx_messageInfo_BlogAddReq.Size(m)
}
func (m *BlogAddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogAddReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlogAddReq proto.InternalMessageInfo

func (m *BlogAddReq) GetArticle() *BlogArticle {
	if m != nil {
		return m.Article
	}
	return nil
}

type BlogUpdateReq struct {
	ObjectID             string   `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	HeadImage            string   `protobuf:"bytes,4,opt,name=headImage,proto3" json:"headImage,omitempty"`
	ReadCount            int32    `protobuf:"varint,5,opt,name=readCount,proto3" json:"readCount,omitempty"`
	ZanCount             int32    `protobuf:"varint,6,opt,name=zanCount,proto3" json:"zanCount,omitempty"`
	ContentMD            string   `protobuf:"bytes,7,opt,name=contentMD,proto3" json:"contentMD,omitempty"`
	ContentHTML          string   `protobuf:"bytes,8,opt,name=contentHTML,proto3" json:"contentHTML,omitempty"`
	Cid                  int32    `protobuf:"varint,9,opt,name=cid,proto3" json:"cid,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogUpdateReq) Reset()         { *m = BlogUpdateReq{} }
func (m *BlogUpdateReq) String() string { return proto.CompactTextString(m) }
func (*BlogUpdateReq) ProtoMessage()    {}
func (*BlogUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{8}
}

func (m *BlogUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogUpdateReq.Unmarshal(m, b)
}
func (m *BlogUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogUpdateReq.Marshal(b, m, deterministic)
}
func (m *BlogUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogUpdateReq.Merge(m, src)
}
func (m *BlogUpdateReq) XXX_Size() int {
	return xxx_messageInfo_BlogUpdateReq.Size(m)
}
func (m *BlogUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlogUpdateReq proto.InternalMessageInfo

func (m *BlogUpdateReq) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

func (m *BlogUpdateReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlogUpdateReq) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BlogUpdateReq) GetHeadImage() string {
	if m != nil {
		return m.HeadImage
	}
	return ""
}

func (m *BlogUpdateReq) GetReadCount() int32 {
	if m != nil {
		return m.ReadCount
	}
	return 0
}

func (m *BlogUpdateReq) GetZanCount() int32 {
	if m != nil {
		return m.ZanCount
	}
	return 0
}

func (m *BlogUpdateReq) GetContentMD() string {
	if m != nil {
		return m.ContentMD
	}
	return ""
}

func (m *BlogUpdateReq) GetContentHTML() string {
	if m != nil {
		return m.ContentHTML
	}
	return ""
}

func (m *BlogUpdateReq) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *BlogUpdateReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type BlogDelReq struct {
	ObjectID             string   `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogDelReq) Reset()         { *m = BlogDelReq{} }
func (m *BlogDelReq) String() string { return proto.CompactTextString(m) }
func (*BlogDelReq) ProtoMessage()    {}
func (*BlogDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{9}
}

func (m *BlogDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogDelReq.Unmarshal(m, b)
}
func (m *BlogDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogDelReq.Marshal(b, m, deterministic)
}
func (m *BlogDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogDelReq.Merge(m, src)
}
func (m *BlogDelReq) XXX_Size() int {
	return xxx_messageInfo_BlogDelReq.Size(m)
}
func (m *BlogDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlogDelReq proto.InternalMessageInfo

func (m *BlogDelReq) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

type StatusResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResp) Reset()         { *m = StatusResp{} }
func (m *StatusResp) String() string { return proto.CompactTextString(m) }
func (*StatusResp) ProtoMessage()    {}
func (*StatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{10}
}

func (m *StatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResp.Unmarshal(m, b)
}
func (m *StatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResp.Marshal(b, m, deterministic)
}
func (m *StatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResp.Merge(m, src)
}
func (m *StatusResp) XXX_Size() int {
	return xxx_messageInfo_StatusResp.Size(m)
}
func (m *StatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResp proto.InternalMessageInfo

func (m *StatusResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StatusResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BlogArticle struct {
	ObjectID             string   `protobuf:"bytes,1,opt,name=objectID,proto3" json:"objectID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cid                  int32    `protobuf:"varint,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	HeadImage            string   `protobuf:"bytes,5,opt,name=headImage,proto3" json:"headImage,omitempty"`
	AuthorName           string   `protobuf:"bytes,6,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorFace           string   `protobuf:"bytes,7,opt,name=authorFace,proto3" json:"authorFace,omitempty"`
	ReadCount            int32    `protobuf:"varint,8,opt,name=readCount,proto3" json:"readCount,omitempty"`
	ZanCount             int32    `protobuf:"varint,9,opt,name=zanCount,proto3" json:"zanCount,omitempty"`
	ContentMD            string   `protobuf:"bytes,10,opt,name=contentMD,proto3" json:"contentMD,omitempty"`
	ContentHTML          string   `protobuf:"bytes,11,opt,name=contentHTML,proto3" json:"contentHTML,omitempty"`
	Ctime                int64    `protobuf:"varint,12,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                int64    `protobuf:"varint,13,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Pcid                 int32    `protobuf:"varint,15,opt,name=pcid,proto3" json:"pcid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogArticle) Reset()         { *m = BlogArticle{} }
func (m *BlogArticle) String() string { return proto.CompactTextString(m) }
func (*BlogArticle) ProtoMessage()    {}
func (*BlogArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_e737bdbda5671783, []int{11}
}

func (m *BlogArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogArticle.Unmarshal(m, b)
}
func (m *BlogArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogArticle.Marshal(b, m, deterministic)
}
func (m *BlogArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogArticle.Merge(m, src)
}
func (m *BlogArticle) XXX_Size() int {
	return xxx_messageInfo_BlogArticle.Size(m)
}
func (m *BlogArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogArticle.DiscardUnknown(m)
}

var xxx_messageInfo_BlogArticle proto.InternalMessageInfo

func (m *BlogArticle) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

func (m *BlogArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlogArticle) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *BlogArticle) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *BlogArticle) GetHeadImage() string {
	if m != nil {
		return m.HeadImage
	}
	return ""
}

func (m *BlogArticle) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *BlogArticle) GetAuthorFace() string {
	if m != nil {
		return m.AuthorFace
	}
	return ""
}

func (m *BlogArticle) GetReadCount() int32 {
	if m != nil {
		return m.ReadCount
	}
	return 0
}

func (m *BlogArticle) GetZanCount() int32 {
	if m != nil {
		return m.ZanCount
	}
	return 0
}

func (m *BlogArticle) GetContentMD() string {
	if m != nil {
		return m.ContentMD
	}
	return ""
}

func (m *BlogArticle) GetContentHTML() string {
	if m != nil {
		return m.ContentHTML
	}
	return ""
}

func (m *BlogArticle) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *BlogArticle) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *BlogArticle) GetPcid() int32 {
	if m != nil {
		return m.Pcid
	}
	return 0
}

func init() {
	proto.RegisterEnum("OrderBy", OrderBy_name, OrderBy_value)
	proto.RegisterType((*BlogIndexReq)(nil), "BlogIndexReq")
	proto.RegisterType((*BlogIndexResp)(nil), "BlogIndexResp")
	proto.RegisterMapType((map[int32]*Category)(nil), "BlogIndexResp.CatEntry")
	proto.RegisterType((*BlogArticleReq)(nil), "BlogArticleReq")
	proto.RegisterType((*BlogArticleResp)(nil), "BlogArticleResp")
	proto.RegisterMapType((map[int32]*Category)(nil), "BlogArticleResp.CatEntry")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*BlogListReq)(nil), "BlogListReq")
	proto.RegisterType((*BlogListResp)(nil), "BlogListResp")
	proto.RegisterType((*BlogAddReq)(nil), "BlogAddReq")
	proto.RegisterType((*BlogUpdateReq)(nil), "BlogUpdateReq")
	proto.RegisterType((*BlogDelReq)(nil), "BlogDelReq")
	proto.RegisterType((*StatusResp)(nil), "StatusResp")
	proto.RegisterType((*BlogArticle)(nil), "BlogArticle")
}

func init() { proto.RegisterFile("blog/blog.proto", fileDescriptor_e737bdbda5671783) }

var fileDescriptor_e737bdbda5671783 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0x1d, 0xc7, 0x49, 0x3c, 0xce, 0x49, 0xab, 0xaa, 0xbf, 0x89, 0x50, 0x6b, 0x19, 0x51,
	0x85, 0x83, 0x0c, 0x0a, 0x5c, 0xa0, 0x8a, 0x9b, 0xb6, 0x01, 0x51, 0xa9, 0x05, 0xc9, 0xc0, 0x05,
	0x97, 0x5b, 0x7b, 0x9b, 0x1a, 0x1c, 0x3b, 0xb1, 0x37, 0x88, 0xf4, 0x45, 0x78, 0x04, 0xc4, 0xab,
	0xf1, 0x0e, 0x48, 0x68, 0x76, 0x37, 0xb1, 0x1d, 0xa0, 0x45, 0x88, 0x9b, 0x68, 0xe6, 0x9b, 0xd9,
	0xc9, 0xcc, 0x7c, 0x33, 0x63, 0xe8, 0x9d, 0xc5, 0xe9, 0xe4, 0x01, 0xfe, 0x78, 0xb3, 0x2c, 0xe5,
	0xa9, 0xdb, 0x85, 0xf6, 0x61, 0x9c, 0x4e, 0x8e, 0x93, 0x90, 0x7d, 0xf2, 0xd9, 0xdc, 0xfd, 0xa2,
	0x41, 0xa7, 0x04, 0xe4, 0x33, 0x32, 0x84, 0x16, 0xcd, 0x78, 0x14, 0xc4, 0x2c, 0xb7, 0x35, 0x47,
	0x1f, 0x5a, 0xa3, 0xb6, 0x87, 0x1e, 0x07, 0x12, 0xf4, 0xd7, 0x56, 0x72, 0x07, 0xf4, 0x80, 0x72,
	0xbb, 0x26, 0x9c, 0xfe, 0xf7, 0x2a, 0x61, 0xbc, 0x23, 0xca, 0x9f, 0x25, 0x3c, 0x5b, 0xfa, 0xe8,
	0x33, 0x38, 0x80, 0xd6, 0x0a, 0x20, 0x7d, 0xd0, 0x3f, 0xb0, 0xa5, 0xad, 0x39, 0xda, 0xd0, 0xf0,
	0x51, 0x24, 0xbb, 0x60, 0x7c, 0xa4, 0xf1, 0x82, 0xd9, 0x35, 0x47, 0x1b, 0x5a, 0x23, 0x13, 0x1f,
	0xb3, 0x49, 0x9a, 0x2d, 0x7d, 0x89, 0xef, 0xd7, 0x9e, 0x68, 0xae, 0x0b, 0xdd, 0x72, 0x1a, 0x6c,
	0x8e, 0x81, 0xd2, 0x28, 0x14, 0x81, 0x4c, 0x1f, 0x45, 0xf7, 0xab, 0x06, 0xbd, 0x8a, 0x53, 0x3e,
	0x23, 0x7b, 0xd0, 0x54, 0x19, 0x0b, 0xcf, 0xcd, 0x72, 0x56, 0x46, 0x72, 0xaf, 0x5c, 0xcd, 0x0d,
	0x6f, 0x23, 0xcc, 0xbf, 0xaf, 0x67, 0x2c, 0x42, 0x08, 0x18, 0x43, 0x04, 0xaa, 0x12, 0xc3, 0x47,
	0x91, 0x10, 0xa8, 0xcf, 0x10, 0xaa, 0x09, 0x48, 0xc8, 0x88, 0x25, 0x74, 0xca, 0x6c, 0x5d, 0x14,
	0x2c, 0x64, 0xf7, 0x1d, 0x58, 0x98, 0xe9, 0x49, 0x94, 0x73, 0x6c, 0xc9, 0x36, 0x34, 0xd2, 0xf3,
	0xf3, 0x9c, 0x71, 0x15, 0x4b, 0x69, 0xf8, 0x34, 0x8f, 0x2e, 0xd9, 0x2a, 0x1c, 0xca, 0x64, 0x07,
	0x8c, 0x34, 0x0b, 0x59, 0x26, 0xe2, 0x75, 0x47, 0x2d, 0xef, 0x15, 0x6a, 0x87, 0x4b, 0x5f, 0xc2,
	0xee, 0x43, 0x39, 0x2a, 0x32, 0x74, 0x3e, 0x23, 0x0e, 0xd4, 0xe3, 0x28, 0xe7, 0xbf, 0x1c, 0x0a,
	0x61, 0x71, 0x1f, 0x03, 0x08, 0x30, 0x0c, 0x31, 0x97, 0x3f, 0x6c, 0xbc, 0xfb, 0xb9, 0x26, 0x47,
	0xf0, 0xed, 0x2c, 0xa4, 0x5c, 0x10, 0x3b, 0x80, 0x56, 0x7a, 0xf6, 0x9e, 0x05, 0xfc, 0x78, 0xac,
	0xd8, 0x5d, 0xeb, 0x64, 0x0b, 0x0c, 0x1e, 0xf1, 0x58, 0x96, 0x62, 0xfa, 0x52, 0xc1, 0xfa, 0x38,
	0x9d, 0xe4, 0xb6, 0xee, 0xe8, 0xd8, 0x1a, 0x94, 0xc9, 0x4d, 0x30, 0x2f, 0x18, 0x0d, 0x8f, 0xa7,
	0x74, 0xc2, 0xec, 0xba, 0xf0, 0x2e, 0x00, 0xb4, 0x66, 0x8c, 0x86, 0x47, 0xe9, 0x22, 0xe1, 0xb6,
	0x21, 0xda, 0x52, 0x00, 0x98, 0xc1, 0x25, 0x4d, 0xa4, 0xb1, 0x21, 0x8c, 0x6b, 0x1d, 0x5f, 0x06,
	0x69, 0xc2, 0x59, 0xc2, 0x4f, 0xc7, 0x76, 0x53, 0xc6, 0x5d, 0x03, 0xc4, 0x01, 0x4b, 0x29, 0x2f,
	0xde, 0x9c, 0x9e, 0xd8, 0x2d, 0x61, 0x2f, 0x43, 0x2b, 0xb2, 0xcd, 0x82, 0xec, 0x6d, 0x68, 0xe4,
	0x9c, 0xf2, 0x45, 0x6e, 0x83, 0x64, 0x4d, 0x6a, 0xee, 0x50, 0xf6, 0x73, 0xcc, 0xe2, 0x6b, 0xba,
	0xe2, 0xee, 0x03, 0xbc, 0x16, 0x6f, 0x04, 0x53, 0x04, 0xea, 0x41, 0x1a, 0x32, 0x35, 0x03, 0x42,
	0x26, 0x36, 0x34, 0xa7, 0x2c, 0xcf, 0xb1, 0x17, 0xb2, 0x73, 0x2b, 0xd5, 0xfd, 0x5e, 0x93, 0x33,
	0xa4, 0x88, 0xf9, 0x8b, 0xee, 0xab, 0x8a, 0xf4, 0xca, 0xf8, 0x0a, 0x3e, 0xea, 0xbf, 0xe3, 0xc3,
	0xd8, 0xe4, 0x63, 0x07, 0x80, 0x2e, 0xf8, 0x45, 0x9a, 0xbd, 0xc4, 0x11, 0x6f, 0x08, 0x73, 0x09,
	0x29, 0xec, 0xcf, 0x69, 0xc0, 0x54, 0xdb, 0x4b, 0x48, 0x95, 0xcf, 0xd6, 0x55, 0x7c, 0x9a, 0x57,
	0xf1, 0x09, 0xd7, 0xf0, 0x69, 0xfd, 0xcc, 0xe7, 0x16, 0x18, 0x01, 0x8f, 0xa6, 0xcc, 0x6e, 0x3b,
	0xda, 0x50, 0xf7, 0xa5, 0x82, 0xe8, 0x54, 0xa0, 0x1d, 0x89, 0x0a, 0x65, 0xbd, 0xd6, 0xbd, 0x62,
	0xad, 0xef, 0x3e, 0x85, 0xa6, 0xda, 0x3c, 0xd2, 0x29, 0x15, 0xd1, 0xff, 0x8f, 0xb4, 0x8b, 0xac,
	0xfb, 0x1a, 0x31, 0xd5, 0xff, 0xf4, 0x6b, 0x28, 0x8a, 0x78, 0x7d, 0x7d, 0xf4, 0x4d, 0x83, 0x3a,
	0xb2, 0x47, 0xf6, 0xc0, 0x10, 0xd7, 0x97, 0x74, 0xca, 0x97, 0x78, 0x3e, 0xe8, 0x56, 0x0f, 0x33,
	0xb9, 0x0f, 0xcd, 0x15, 0xd3, 0xbd, 0xea, 0x95, 0x9b, 0x0f, 0xfa, 0x9b, 0x67, 0x8f, 0xdc, 0x82,
	0x3a, 0x1e, 0x00, 0x22, 0x77, 0x57, 0x9d, 0x99, 0x41, 0xc7, 0xab, 0x5c, 0x86, 0x5d, 0xd0, 0x0f,
	0xc2, 0x90, 0x58, 0x5e, 0xb1, 0xfd, 0x03, 0xcb, 0x2b, 0x0d, 0xe4, 0x2e, 0xe8, 0x63, 0x16, 0x2b,
	0x07, 0x39, 0xce, 0x55, 0x87, 0xdb, 0xd0, 0x90, 0xeb, 0x4f, 0x64, 0xba, 0xeb, 0x5b, 0x50, 0x71,
	0x3b, 0x6b, 0x88, 0x8f, 0xd8, 0xa3, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x7a, 0x3a, 0x3f,
	0xd7, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogClient is the client API for Blog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogClient interface {
	// 首页
	Index(ctx context.Context, in *BlogIndexReq, opts ...grpc.CallOption) (*BlogIndexResp, error)
	// 文章详情页
	Article(ctx context.Context, in *BlogArticleReq, opts ...grpc.CallOption) (*BlogArticleResp, error)
	// 文章列表页
	List(ctx context.Context, in *BlogListReq, opts ...grpc.CallOption) (*BlogListResp, error)
	// 新增文章
	Add(ctx context.Context, in *BlogAddReq, opts ...grpc.CallOption) (*StatusResp, error)
	// 删除文章
	Del(ctx context.Context, in *BlogDelReq, opts ...grpc.CallOption) (*StatusResp, error)
	// 更新文章
	Update(ctx context.Context, in *BlogUpdateReq, opts ...grpc.CallOption) (*StatusResp, error)
}

type blogClient struct {
	cc *grpc.ClientConn
}

func NewBlogClient(cc *grpc.ClientConn) BlogClient {
	return &blogClient{cc}
}

func (c *blogClient) Index(ctx context.Context, in *BlogIndexReq, opts ...grpc.CallOption) (*BlogIndexResp, error) {
	out := new(BlogIndexResp)
	err := c.cc.Invoke(ctx, "/Blog/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) Article(ctx context.Context, in *BlogArticleReq, opts ...grpc.CallOption) (*BlogArticleResp, error) {
	out := new(BlogArticleResp)
	err := c.cc.Invoke(ctx, "/Blog/Article", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) List(ctx context.Context, in *BlogListReq, opts ...grpc.CallOption) (*BlogListResp, error) {
	out := new(BlogListResp)
	err := c.cc.Invoke(ctx, "/Blog/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) Add(ctx context.Context, in *BlogAddReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/Blog/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) Del(ctx context.Context, in *BlogDelReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/Blog/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogClient) Update(ctx context.Context, in *BlogUpdateReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/Blog/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServer is the server API for Blog service.
type BlogServer interface {
	// 首页
	Index(context.Context, *BlogIndexReq) (*BlogIndexResp, error)
	// 文章详情页
	Article(context.Context, *BlogArticleReq) (*BlogArticleResp, error)
	// 文章列表页
	List(context.Context, *BlogListReq) (*BlogListResp, error)
	// 新增文章
	Add(context.Context, *BlogAddReq) (*StatusResp, error)
	// 删除文章
	Del(context.Context, *BlogDelReq) (*StatusResp, error)
	// 更新文章
	Update(context.Context, *BlogUpdateReq) (*StatusResp, error)
}

// UnimplementedBlogServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServer struct {
}

func (*UnimplementedBlogServer) Index(ctx context.Context, req *BlogIndexReq) (*BlogIndexResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (*UnimplementedBlogServer) Article(ctx context.Context, req *BlogArticleReq) (*BlogArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Article not implemented")
}
func (*UnimplementedBlogServer) List(ctx context.Context, req *BlogListReq) (*BlogListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBlogServer) Add(ctx context.Context, req *BlogAddReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedBlogServer) Del(ctx context.Context, req *BlogDelReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (*UnimplementedBlogServer) Update(ctx context.Context, req *BlogUpdateReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterBlogServer(s *grpc.Server, srv BlogServer) {
	s.RegisterService(&_Blog_serviceDesc, srv)
}

func _Blog_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blog/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).Index(ctx, req.(*BlogIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_Article_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).Article(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blog/Article",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).Article(ctx, req.(*BlogArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blog/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).List(ctx, req.(*BlogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blog/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).Add(ctx, req.(*BlogAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogDelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blog/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).Del(ctx, req.(*BlogDelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blog_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlogUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blog/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServer).Update(ctx, req.(*BlogUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Blog",
	HandlerType: (*BlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _Blog_Index_Handler,
		},
		{
			MethodName: "Article",
			Handler:    _Blog_Article_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Blog_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Blog_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Blog_Del_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Blog_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/blog.proto",
}
